name: Deploy Walexkino ecommerce site

on:
  push:
    branches:
      - master


env:
  AZURE_WEBAPP_NAME: klodkode
  AZURE_WEBAPP_PATH: '.'
  PHP_VERSION: '7.4'


jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@master

      - name: Login via Azure CLI
        uses: azure/actions/login@v1
        with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl #optional
          ini-values: "post_max_size=256M" #optional

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package:  '${{ env.AZURE_WEBAPP_PATH }}/myapp'
        